spring:
  application:
    name: taco-cloud
  datasource:
    url: jdbc:postgresql://localhost:5432/tacocloud
    username: postgres
    password: 159753
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: <facebook client id>
            client-secret: <facebook client secret>
            scope: email, public_profile
  data:
    rest:
      base-path: /data-api